spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easy-admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations:
        - optional:classpath*:sql/role.sql
        - optional:classpath*:sql/menu.sql
      mode: always
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
