server:
  port: 8080
spring:
  profiles:
    active: '@env@'
    include: auth-${spring.profiles.active}
springdoc:
  api-docs:
    enabled: false
app:
  captcha:
    mode: redis
    key-prefix: x-cloud:captcha
    timeout: 30s
